

(cl-defun r7rs:add-cxr ()
  (r7rs:add-keywords
   'r7rs:face-function
   '((1 . caaar)
     (1 . caadr)
     (1 . cadar)
     (1 . caddr)
     (1 . cdaar)
     (1 . cdadr)
     (1 . cddar)
     (1 . cdddr)
     (1 . caaaar)
     (1 . caaadr)
     (1 . caadar)
     (1 . caaddr)
     (1 . cadaar)
     (1 . cadadr)
     (1 . caddar)
     (1 . cadddr)
     (1 . cdaaar)
     (1 . cdaadr)
     (1 . cdadar)
     (1 . cdaddr)
     (1 . cddaar)
     (1 . cddadr)
     (1 . cdddar)
     (1 . cddddr))))

(provide 'r7rs-cxr)
